### PR TITLE
fix: api mode standard missing field added

### PR DESCRIPTION
**Pull request by sanket-naphade**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by babu-srinivasan** [comment]
Hi
Thanks for submitting the PR. 
The StreamArn and TransactionId fields have been deprecated and removed from the call event processor. The lca-client utility does not need to write these fields to KDS (integration layer). Could you please confirm and resubmit PR without these fields. Thanks

**Comment by sanket-naphade** [comment]
Hi Babu,

The field was added because I noticed the following error in cloudwatch for lambda "CallEventProcessorFunction" when I ran the script with "api-mode=standard".
 
StreamArn

1. transcript api mutation exception: 'StreamArn'
2. event processor error: 'StreamArn'
3. `Traceback (most recent call last):\n  File \"/var/task/lambda_function.py\", line 148, in handler\n    raise error\n  File \"/var/task/event_processor/transcribe.py\", line 736, in execute_process_event_api_mutation\n    add_transcript_tasks = add_transcript_segments(\n  File \"/var/task/event_processor/transcribe.py\", line 147, in add_transcript_segments\n    **transform_segment_to_add_transcript({**message}),\n  File \"/var/task/event_processor/transcribe.py\", line 110, in transform_segment_to_add_transcript\n    stream_arn: str = message[\"StreamArn\"]\nKeyError: 'StreamArn'`

TransactionId

1. transcript api mutation exception: 'TransactionId'
2. event processor error: 'TransactionId'
3. `Traceback (most recent call last):\n  File \"/var/task/lambda_function.py\", line 148, in handler\n    raise error\n  File \"/var/task/event_processor/transcribe.py\", line 736, in execute_process_event_api_mutation\n    add_transcript_tasks = add_transcript_segments(\n  File \"/var/task/event_processor/transcribe.py\", line 147, in add_transcript_segments\n    **transform_segment_to_add_transcript({**message}),\n  File \"/var/task/event_processor/transcribe.py\", line 111, in transform_segment_to_add_transcript\n    transaction_id: str = message[\"TransactionId\"]\nKeyError: 'TransactionId'"`

Then I compared the logs to the record of the actual call I made using the chime voice connection and I noticed the field StreamArn: "<DEPRECATED>" and TransactionId was logged in payload.

Although I am unsure whether there is a problem or change that must be made on the lambda side, but as quick workaround I found this way to resolve the issue.

quick note: we are currently using LCA `V0.5.2`.

Thanks.

**Comment by babu-srinivasan** [comment]
Thanks for sharing the details. StreamArn and TransactionId fields were removed in v0.6.0 which is the current release version in github. https://github.com/aws-samples/amazon-transcribe-live-call-analytics/releases/tag/v0.6.0 The lca-client utility (currently in feature/utilities branch) was written for v0.6.0 version - that explains the errors you are getting with your v0.5.2 version of LCA. Since the feature/utilities branch will eventually be merged with main LCA >v0.6.0 (in the next minor release), introducing these deprecated fields now into the branch will re-introduce them back into the next release. Is there anyway you distribute your workaround for v0.5.2 locally while we commit the additional fields (AgentId & Metadatajson) into the feature/utilities branch. Thanks

**Comment by sanket-naphade** [comment]
I made the changes.
Please ignore if it's already done on your end. Thanks.

**Comment by babu-srinivasan** [comment]
Merged the PR. Thanks!

**Pull request merged**
